spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
  profiles:
    include: oauth
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

server:
  servlet:
    encoding:
      force-response: true